"""add product columns

Revision ID: 330ea240c152
Revises: 738090b577b3
Create Date: 2023-12-07 18:15:31.075715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '330ea240c152'
down_revision: Union[str, None] = '738090b577b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('taste', sa.TEXT(), nullable=True))
    op.add_column('products', sa.Column('aroma', sa.TEXT(), nullable=True))
    op.add_column('products', sa.Column('combination', sa.TEXT(), nullable=True))
    op.add_column('products', sa.Column('color', sa.TEXT(), nullable=True))
    op.add_column('products', sa.Column('iiko_id', sa.String(length=50), nullable=True))
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('products', 'iiko_id')
    op.drop_column('products', 'color')
    op.drop_column('products', 'combination')
    op.drop_column('products', 'aroma')
    op.drop_column('products', 'taste')
    # ### end Alembic commands ###
