"""update

Revision ID: ab22936a180b
Revises: 60d1eadd280d
Create Date: 2023-11-30 05:09:13.413661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab22936a180b'
down_revision: Union[str, None] = '60d1eadd280d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cart', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
    op.add_column('types', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'types', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'types', type_='foreignkey')
    op.drop_column('types', 'category_id')
    op.alter_column('cart', 'total_price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
    # ### end Alembic commands ###
